name: Example Workflow

on: 
  workflow_dispatch:
    
jobs:
  example_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get our files
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Check out the VM
        run: |
          echo $ ls -la
          ls -la
          echo $ whoami
          whoami 
      - name: Check out cassini
        run: |
          echo $ ssh mulch@cassini.cs.kent.edu ls -la
          ssh mulch@cassini.cs.kent.edu ls -la 
          echo $ ssh mulch@cassini.cs.kent.edu whoami
          ssh mulch@cassini.cs.kent.edu whoami 
          echo $ ssh mulch@cassini.cs.kent.edu hostname
          ssh mulch@cassini.cs.kent.edu hostname