name: Unit Test Workflow

on: 
  workflow_dispatch:
  push:

env:
  HOST: cassini.cs.kent.edu
  USER: mulch
  TARGET: mulch@cassini.cs.kent.edu
  RUN: ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no mulch@cassini.cs.kent.edu
  COPY: scp -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

    
jobs:
  unit_test_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get our files
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Check out the VM
        run: |
          echo $ ls -la
          ls -la
          echo $ whoami
          whoami 
      - name: Test the numbers library on the VM
        run: |
          node test_calcNumbers.js
    
      